using System;

namespace SolScript.Compiler.Native
{
    /// <summary>
    ///     This attribute annotates classes generated by the native compiler when mapping SolScript classes to native classes.
    /// </summary>
    public sealed class SolNativeCompilerGeneratedAttribute : Attribute {}
}