//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolScript.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolScript.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The class definition &quot;{0}&quot; is not valid..
        /// </summary>
        internal static string Err_ClassDefinitionNotValid {
            get {
                return ResourceManager.GetString("Err_ClassDefinitionNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The class &quot;{0}&quot; representing the native type &quot;{1}&quot; is described by the &quot;{2}&quot; type. However, the descriptor does not implement the ISolTypeDescriptor interface which is required for type descriptors describing another type then itself..
        /// </summary>
        internal static string Err_DescriptorNotFound {
            get {
                return ResourceManager.GetString("Err_DescriptorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The class &quot;{0}&quot; exists multiple times..
        /// </summary>
        internal static string Err_DuplicateClass {
            get {
                return ResourceManager.GetString("Err_DuplicateClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The class &quot;{0}&quot; is described multiple times..
        /// </summary>
        internal static string Err_DuplicateClassDescribed {
            get {
                return ResourceManager.GetString("Err_DuplicateClassDescribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The class descriptor &quot;{0}&quot; describes multiple classes..
        /// </summary>
        internal static string Err_DuplicateClassDescriptor {
            get {
                return ResourceManager.GetString("Err_DuplicateClassDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The class &quot;{0}&quot; has multiple fields with the name &quot;{1}&quot;. Overloading is not supported..
        /// </summary>
        internal static string Err_DuplicateClassField {
            get {
                return ResourceManager.GetString("Err_DuplicateClassField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The class &quot;{0}&quot; has multiple functions with the name &quot;{1}&quot;. Overloading is not supported..
        /// </summary>
        internal static string Err_DuplicateClassFunction {
            get {
                return ResourceManager.GetString("Err_DuplicateClassFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are multiple global fields with the name &quot;{1}&quot;. Overloading is not supported..
        /// </summary>
        internal static string Err_DuplicateGlobalField {
            get {
                return ResourceManager.GetString("Err_DuplicateGlobalField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are multiple global fields with the name &quot;{1}&quot;. Overloading is not supported..
        /// </summary>
        internal static string Err_DuplicateGlobalFunction {
            get {
                return ResourceManager.GetString("Err_DuplicateGlobalFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression &quot;{0}&quot; is not a constant..
        /// </summary>
        internal static string Err_ExpressionIsNotConstant {
            get {
                return ResourceManager.GetString("Err_ExpressionIsNotConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : The node name &quot;{1}&quot; is not allowed for this element. Allowed is/are: &quot;{2}&quot;.
        /// </summary>
        internal static string Err_FactoryInvalidNodeName {
            get {
                return ResourceManager.GetString("Err_FactoryInvalidNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : The node &quot;{1}&quot; does not have a child node with the name &quot;{1}&quot;..
        /// </summary>
        internal static string Err_FactoryMissingChild {
            get {
                return ResourceManager.GetString("Err_FactoryMissingChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to build a delegate of type &quot;{0}&quot; for function &quot;{1}&quot;..
        /// </summary>
        internal static string Err_FailedToBuildDelegate {
            get {
                return ResourceManager.GetString("Err_FailedToBuildDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to build the dynamic mapping..
        /// </summary>
        internal static string Err_FailedToBuildDynamicMapping {
            get {
                return ResourceManager.GetString("Err_FailedToBuildDynamicMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to build function from native constructor &quot;{0}&quot;..
        /// </summary>
        internal static string Err_FailedToBuildNativeConstructor {
            get {
                return ResourceManager.GetString("Err_FailedToBuildNativeConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to build field from native field &quot;{0}&quot;..
        /// </summary>
        internal static string Err_FailedToBuildNativeField {
            get {
                return ResourceManager.GetString("Err_FailedToBuildNativeField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to build function from native method &quot;{0}&quot;..
        /// </summary>
        internal static string Err_FailedToBuildNativeFunction {
            get {
                return ResourceManager.GetString("Err_FailedToBuildNativeFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to build parameter from native parameter &quot;{0}&quot;..
        /// </summary>
        internal static string Err_FailedToBuildNativeParameter {
            get {
                return ResourceManager.GetString("Err_FailedToBuildNativeParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SolScript grammar could not be generated. Did you modify the grammar? If so consider reading up on the NodeParser as there are slight but important differences to how Irony works by default..
        /// </summary>
        internal static string Err_FailedToBuildSolScriptGrammar {
            get {
                return ResourceManager.GetString("Err_FailedToBuildSolScriptGrammar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create annotations on global field &quot;{1}&quot;..
        /// </summary>
        internal static string Err_FailedToCreateGlobalFieldAnnotations {
            get {
                return ResourceManager.GetString("Err_FailedToCreateGlobalFieldAnnotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create annotations on global function &quot;{1}&quot;..
        /// </summary>
        internal static string Err_FailedToCreateGlobalFunctionAnnotations {
            get {
                return ResourceManager.GetString("Err_FailedToCreateGlobalFunctionAnnotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to declare global field &quot;{0}&quot;..
        /// </summary>
        internal static string Err_FailedToDeclareGlobalField {
            get {
                return ResourceManager.GetString("Err_FailedToDeclareGlobalField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to declare global function &quot;{0}&quot;..
        /// </summary>
        internal static string Err_FailedToDeclareGlobalFunction {
            get {
                return ResourceManager.GetString("Err_FailedToDeclareGlobalFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get the native object of class &quot;{0}&quot;..
        /// </summary>
        internal static string Err_FailedToGetNativeClassObject {
            get {
                return ResourceManager.GetString("Err_FailedToGetNativeClassObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse the file &quot;{0}&quot;. See inner exception for details..
        /// </summary>
        internal static string Err_FailedToParseFile {
            get {
                return ResourceManager.GetString("Err_FailedToParseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tried to build the global function &quot;{0}&quot; from a constructor of native type &quot;{1}&quot;. Constructors cannot be global functions..
        /// </summary>
        internal static string Err_GlobalFunctionCannotBeNativeConstructor {
            get {
                return ResourceManager.GetString("Err_GlobalFunctionCannotBeNativeConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The global member &quot;{0}&quot; defined in global type descriptor &quot;{1}&quot; is not static..
        /// </summary>
        internal static string Err_GlobalMemberMustBeStatic {
            get {
                return ResourceManager.GetString("Err_GlobalMemberMustBeStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reference to the described object of class &quot;{0}&quot; is invalid..
        /// </summary>
        internal static string Err_InvalidClassDescribedObjectReference {
            get {
                return ResourceManager.GetString("Err_InvalidClassDescribedObjectReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reference to the descriptor object of class &quot;{1}&quot; is invalid..
        /// </summary>
        internal static string Err_InvalidClassDescriptorObjectReference {
            get {
                return ResourceManager.GetString("Err_InvalidClassDescriptorObjectReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid function call parameters for &quot;{0}&quot;..
        /// </summary>
        internal static string Err_InvalidFunctionCallParameters {
            get {
                return ResourceManager.GetString("Err_InvalidFunctionCallParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tried to index a &quot;{0}&quot; value by a &quot;{1}&quot; value..
        /// </summary>
        internal static string Err_InvalidIndexerType {
            get {
                return ResourceManager.GetString("Err_InvalidIndexerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tried to index a &quot;{0}&quot; value..
        /// </summary>
        internal static string Err_InvalidIndexType {
            get {
                return ResourceManager.GetString("Err_InvalidIndexType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marshalling requires a type for each value - Got {0} SolScript values and {1} native types, wich will be marshalled to an array of length {2} containing the native marshaller values. Marshalling will start at value array index {3} and marshal {4} values. The offset in the target array is {5}..
        /// </summary>
        internal static string Err_MarshallingArrayMismatch {
            get {
                return ResourceManager.GetString("Err_MarshallingArrayMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The class &quot;{0}&quot; does not have a constructor..
        /// </summary>
        internal static string Err_NoClassConstructor {
            get {
                return ResourceManager.GetString("Err_NoClassConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given type &quot;{0}&quot; is not a subclass of &quot;{1}&quot;..
        /// </summary>
        internal static string Err_NotSubclassOf {
            get {
                return ResourceManager.GetString("Err_NotSubclassOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} operator is not valid in global context..
        /// </summary>
        internal static string Err_NotValidInGlobal {
            get {
                return ResourceManager.GetString("Err_NotValidInGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An I/O error occured while reading source file &quot;{0}&quot;..
        /// </summary>
        internal static string Err_SourceFileIOError {
            get {
                return ResourceManager.GetString("Err_SourceFileIOError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source file &quot;{0}&quot; is invalid..
        /// </summary>
        internal static string Err_SourceFileIsInvalid {
            get {
                return ResourceManager.GetString("Err_SourceFileIsInvalid", resourceCulture);
            }
        }
    }
}
